CREATE DATABASE IF NOT EXISTS CrashData;

USE CrashData;

CREATE TABLE IF NOT EXISTS CrashPoints (
    id INT AUTO_INCREMENT PRIMARY KEY,
    crash_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    crash_point VARCHAR(10)
);
